export const TeachersInfo = [
  {
    fname: 'Amina',
    lname: 'Bashir',
    cell: '+923213334444',
    teachingEmail: 'amina.bashir@orionedu.net',
    profileimg:
      'https://static.vecteezy.com/system/resources/previews/002/002/257/non_2x/beautiful-woman-avatar-character-icon-free-vector.jpg',
    department: 'Psychology',
    gmail: 'amina.bashir@gmail.com',
    address: '678 Hillside Drive, Karachi',
    gender: 'Female',
  },
  {
    fname: 'Sara',
    lname: 'Ahmed',
    cell: '+923119876543',
    teachingEmail: 'sara.ahmed@orionedu.net',
    profileimg:
      'https://static.vecteezy.com/system/resources/previews/002/002/257/non_2x/beautiful-woman-avatar-character-icon-free-vector.jpg',
    department: 'Physics',
    gmail: 'sara.ahmed@gmail.com',
    address: '456 Market Road, Karachi',
    gender: 'Female',
  },
  {
    fname: 'Bilal',
    lname: 'Majeed',
    cell: '+923158889999',
    teachingEmail: 'bilal.majeed@orionedu.net',
    profileimg:
      'https://static.vecteezy.com/system/resources/previews/024/183/502/original/male-avatar-portrait-of-a-young-man-with-a-beard-illustration-of-male-character-in-modern-color-style-vector.jpg',
    department: 'Sociology',
    gmail: 'bilal.majeed@gmail.com',
    address: '123 Valley Street, Islamabad',
    gender: 'Male',
  },
  {
    fname: 'Fatima',
    lname: 'Malik',
    cell: '+923101112222',
    teachingEmail: 'fatima.malik@orionedu.net',
    profileimg:
      'https://static.vecteezy.com/system/resources/previews/002/002/257/non_2x/beautiful-woman-avatar-character-icon-free-vector.jpg',
    department: 'History',
    gmail: 'fatima.malik@gmail.com',
    address: '890 Forest Lane, Islamabad',
    gender: 'Female',
  },
  {
    fname: 'Naveed',
    lname: 'Hassan',
    cell: '+923442223333',
    teachingEmail: 'naveed.hassan@orionedu.net',
    profileimg:
      'https://static.vecteezy.com/system/resources/previews/024/183/502/original/male-avatar-portrait-of-a-young-man-with-a-beard-illustration-of-male-character-in-modern-color-style-vector.jpg',
    department: 'English',
    gmail: 'naveed.hassan@gmail.com',
    address: '345 Lake View, Lahore',
    gender: 'Male',
  },
  {
    fname: 'Ahmed',
    lname: 'Raza',
    cell: '+923455556666',
    teachingEmail: 'ahmed.raza@orionedu.net',
    profileimg:
      'https://static.vecteezy.com/system/resources/previews/024/183/502/original/male-avatar-portrait-of-a-young-man-with-a-beard-illustration-of-male-character-in-modern-color-style-vector.jpg',
    department: 'Mathematics',
    gmail: 'ahmed.raza@gmail.com',
    address: '789 Liberty Avenue, Islamabad',
    gender: 'Male',
  },
  {
    fname: 'Sadia',
    lname: 'Iqbal',
    cell: '+923325554444',
    teachingEmail: 'sadia.iqbal@orionedu.net',
    profileimg:
      'https://static.vecteezy.com/system/resources/previews/002/002/257/non_2x/beautiful-woman-avatar-character-icon-free-vector.jpg',
    department: 'Economics',
    gmail: 'sadia.iqbal@gmail.com',
    address: '456 Ridge Road, Lahore',
    gender: 'Female',
  },
  {
    fname: 'Usman',
    lname: 'Khalid',
    cell: '+923337778888',
    teachingEmail: 'usman.khalid@orionedu.net',
    profileimg:
      'https://static.vecteezy.com/system/resources/previews/024/183/502/original/male-avatar-portrait-of-a-young-man-with-a-beard-illustration-of-male-character-in-modern-color-style-vector.jpg',
    department: 'Chemistry',
    gmail: 'usman.khalid@gmail.com',
    address: '234 Park Avenue, Karachi',
    gender: 'Male',
  },
  {
    fname: 'Ayesha',
    lname: 'Ali',
    cell: '+923229998888',
    teachingEmail: 'ayesha.ali@orionedu.net',
    profileimg:
      'https://static.vecteezy.com/system/resources/previews/002/002/257/non_2x/beautiful-woman-avatar-character-icon-free-vector.jpg',
    department: 'Biology',
    gmail: 'ayesha.ali@gmail.com',
    address: '567 Garden Street, Lahore',
    gender: 'Female',
  },
  {
    fname: 'Saim',
    lname: 'Akhtar',
    cell: '+923461234567',
    teachingEmail: 'saim.akhtar@orionedu.net',
    profileimg:
      'https://static.vecteezy.com/system/resources/previews/024/183/502/original/male-avatar-portrait-of-a-young-man-with-a-beard-illustration-of-male-character-in-modern-color-style-vector.jpg',
    department: 'Political Science',
    gmail: 'saim.akhtar@gmail.com',
    address: '890 Mountain View, Islamabad',
    gender: 'Male',
  },
  {
    fname: 'Madiha',
    lname: 'Haider',
    cell: '+923139876543',
    teachingEmail: 'madiha.haider@orionedu.net',
    profileimg:
      'https://static.vecteezy.com/system/resources/previews/002/002/257/non_2x/beautiful-woman-avatar-character-icon-free-vector.jpg',
    department: 'Environmental Science',
    gmail: 'madiha.haider@gmail.com',
    address: '456 Skyline Street, Karachi',
    gender: 'Female',
  },
  {
    fname: 'Tariq',
    lname: 'Aziz',
    cell: '+923455557777',
    teachingEmail: 'tariq.aziz@orionedu.net',
    profileimg:
      'https://static.vecteezy.com/system/resources/previews/024/183/502/original/male-avatar-portrait-of-a-young-man-with-a-beard-illustration-of-male-character-in-modern-color-style-vector.jpg',
    department: 'Geography',
    gmail: 'tariq.aziz@gmail.com',
    address: '345 Ocean View, Lahore',
    gender: 'Male',
  },
  {
    fname: 'Sana',
    lname: 'Khan',
    cell: '+923218889999',
    teachingEmail: 'sana.khan@orionedu.net',
    profileimg:
      'https://static.vecteezy.com/system/resources/previews/002/002/257/non_2x/beautiful-woman-avatar-character-icon-free-vector.jpg',
    department: 'Social Work',
    gmail: 'sana.khan@gmail.com',
    address: '678 River Road, Islamabad',
    gender: 'Female',
  },
  {
    fname: 'Nasir',
    lname: 'Ali',
    cell: '+923332223333',
    teachingEmail: 'nasir.ali@orionedu.net',
    profileimg:
      'https://static.vecteezy.com/system/resources/previews/024/183/502/original/male-avatar-portrait-of-a-young-man-with-a-beard-illustration-of-male-character-in-modern-color-style-vector.jpg',
    department: 'Anthropology',
    gmail: 'nasir.ali@gmail.com',
    address: '123 Hilltop Drive, Karachi',
    gender: 'Male',
  },
  {
    fname: 'Hina',
    lname: 'Riaz',
    cell: '+923104445555',
    teachingEmail: 'hina.riaz@orionedu.net',
    profileimg:
      'https://static.vecteezy.com/system/resources/previews/002/002/257/non_2x/beautiful-woman-avatar-character-icon-free-vector.jpg',
    department: 'Linguistics',
    gmail: 'hina.riaz@gmail.com',
    address: '456 Meadow Lane, Lahore',
    gender: 'Female',
  },
]
